AWSTemplateFormatVersion: '2010-09-09'
Description: Static Website Hosting with Contact Form Handling via Lambda, SES, SNS

Parameters:
  DomainName:
    Type: String
    Description: e.g. www.example.com
  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for your domain
  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate in us-east-1 for CloudFront
  NotificationEmail:
    Type: String
    Description: Email address to notify on form submission
  NotificationPhone:
    Type: String
    Description: Phone number for SMS (e.g. +15551234567)
  TagProject:
    Type: String
    Description: Logical project identifier (e.g. PersonalWebsite)
  TagOwner:
    Type: String
    Description: Resource owner (e.g. Oleksandr)
  TagEnvironment:
    Type: String
    Description: Deployment environment (e.g. Production)
  TagRegion:
    Type: String
    Description: AWS region (e.g. us-west-2)

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: "s3/"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref TagEnvironment
        - Key: Project
          Value: !Ref TagProject
        - Key: Owner
          Value: !Ref TagOwner
        - Key: Region
          Value: !Ref TagRegion

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${DomainName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${DomainName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: [ !Ref DomainName ]
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: s3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD ]
          CachedMethods: [ GET, HEAD ]
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          ForwardedValues:
            QueryString: false
            Headers:
              - Origin
        Origins:
          - Id: s3Origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            S3OriginConfig: { }
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        Logging:
          Bucket: !GetAtt LoggingBucket.DomainName
          IncludeCookies: false
          Prefix: "cloudfront/"
      Tags:
        - Key: Environment
          Value: !Ref TagEnvironment
        - Key: Project
          Value: !Ref TagProject
        - Key: Owner
          Value: !Ref TagOwner
        - Key: Region
          Value: !Ref TagRegion

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ContactFormTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail
        - Protocol: sms
          Endpoint: !Ref NotificationPhone
      Tags:
        - Key: Environment
          Value: !Ref TagEnvironment
        - Key: Project
          Value: !Ref TagProject
        - Key: Owner
          Value: !Ref TagOwner
        - Key: Region
          Value: !Ref TagRegion

  ContactFormFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-ContactFormFunctionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ContactFormPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !GetAtt ContactFormTopic.TopicArn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Tags:
        - Key: Environment
          Value: !Ref TagEnvironment
        - Key: Project
          Value: !Ref TagProject
        - Key: Owner
          Value: !Ref TagOwner
        - Key: Region
          Value: !Ref TagRegion

  ContactFormFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ContactFormHandler
      Handler: index.handler
      Role: !GetAtt ContactFormFunctionRole.Arn
      Runtime: python3.12
      Timeout: 10
      Environment:
        Variables:
          CONTACT_TOPIC_ARN: !Ref ContactFormTopic
          ALLOWED_ORIGIN: !Sub "https://${DomainName}"
      Tags:
        - Key: Environment
          Value: !Ref TagEnvironment
        - Key: Project
          Value: !Ref TagProject
        - Key: Owner
          Value: !Ref TagOwner
        - Key: Region
          Value: !Ref TagRegion
      Code:
        ZipFile: !Sub |
          import json
          import boto3
          import os

          sns = boto3.client("sns")
          origin = os.environ["ALLOWED_ORIGIN"]
          topic_arn = os.environ["CONTACT_TOPIC_ARN"]

          def handler(event, context):
              try:
                  request_origin = event.get("headers", {}).get("origin", "")
                  if request_origin != origin:
                      return {
                          "statusCode": 403,
                          "body": json.dumps({"message": "Forbidden"})
                      }

                  method = event.get("requestContext", {}).get("http", {}).get("method")
                  if method == "OPTIONS":
                      return {
                          "statusCode": 204,
                          "body": ""
                      }

                  body = json.loads(event["body"])
                  name = body.get("name")
                  email = body.get("email")
                  message = body.get("message")

                  if not name or not email or not message:
                      return {
                          "statusCode": 400,
                          "body": json.dumps({"message": "Missing form fields"})
                      }

                  text = f"New contact form submission:\nName: {name}\nEmail: {email}\nMessage: {message}"

                  sns.publish(
                      TopicArn=topic_arn,
                      Message=text,
                      Subject="New Contact Form Submission"
                  )

                  return {
                      "statusCode": 200,
                      "body": json.dumps({"message": "Message sent"})
                  }
              except Exception as e:
                  return {
                      "statusCode": 500,
                      "body": json.dumps({"message": str(e)})
                  }


  ContactFormFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt ContactFormFunction.Arn
      Cors:
        AllowOrigins:
          - !Sub "https://${DomainName}"
        AllowMethods: [ "POST" ]
        AllowHeaders: [ "Content-Type" ]
        MaxAge: 86400

  ContactFormFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref ContactFormFunction
      Principal: "*"
      FunctionUrlAuthType: NONE

  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-logs"
      OwnershipControls: # 👈 Required
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: false     # 👈 Allow ACLs to be honored
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref TagEnvironment
        - Key: Project
          Value: !Ref TagProject
        - Key: Owner
          Value: !Ref TagOwner
        - Key: Region
          Value: !Ref TagRegion

  ContactFormFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ContactFormFunction}"
      RetentionInDays: 14  # or 3, 7, 30, 90, etc.
      Tags:
        - Key: Environment
          Value: !Ref TagEnvironment
        - Key: Project
          Value: !Ref TagProject
        - Key: Owner
          Value: !Ref TagOwner
        - Key: Region
          Value: !Ref TagRegion

Outputs:
  WebsiteURL:
    Value: !Sub "https://${DomainName}"
  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: Direct CloudFront URL
  FormLambdaName:
    Value: !Ref ContactFormFunction
  NotificationTopicArn:
    Value: !Ref ContactFormTopic
  LoggingBucketName:
    Value: !Ref LoggingBucket
    Description: S3 bucket where logs for S3 + CloudFront are stored
  ContactFormFunctionRoleName:
    Value: !Ref ContactFormFunctionRole
    Description: IAM Role name for the Lambda contact form handler
  LambdaLogGroupName:
    Value: !Ref ContactFormFunctionLogGroup
    Description: CloudWatch log group for the contact form Lambda
  ContactFormEndpoint:
    Description: Public HTTPS endpoint for contact form
    Value: !GetAtt ContactFormFunctionUrl.FunctionUrl