AWSTemplateFormatVersion: '2010-09-09'
Description: Static website on S3 + CloudFront + Route53 with tags

Parameters:
  DomainName:
    Type: String
    Description: e.g. www.example.com
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID (not name)
  CertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1 for the domain

  Environment:
    Type: String
    Default: production
    AllowedValues:
      - dev
      - staging
      - production
  Project:
    Type: String
    Default: StaticWebsite
  Owner:
    Type: String
    Default: WebTeam

Tags: &Tags
  - Key: Environment
    Value: !Ref Environment
  - Key: Project
    Value: !Ref Project
  - Key: Owner
    Value: !Ref Owner

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}"
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags: *Tags

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: "s3:GetObject"
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteDistribution}"
      Tags: *Tags

  WebsiteOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      Name: !Sub "${DomainName}-OAC"
      OriginAccessControlConfig:
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: Access control for S3 origin
      Tags: *Tags

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD ]
          CachedMethods: [ GET, HEAD ]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig: { }
            OriginAccessControlId: !Ref WebsiteOAC
        PriceClass: PriceClass_100
      Tags: *Tags

  WebsiteDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront global zone ID
      # Note: Route53 RecordSet doesn't support Tags directly